moi = 6.883
weight = 115
has-canivore = false

# if battery is in back, i.e., tusk
battery-back = false

deviceIds.front-left-steer = 1
deviceIds.front-left-drive = 2
deviceIds.front-left-steer-encoder = 3
deviceIds.front-right-steer = 4
deviceIds.front-right-drive = 5
deviceIds.front-right-steer-encoder = 6
deviceIds.back-left-steer = 10
deviceIds.back-left-drive = 11
deviceIds.back-left-steer-encoder = 12
deviceIds.back-right-steer = 7
deviceIds.back-right-drive = 8
deviceIds.back-right-steer-encoder = 9
deviceIds.pigeon = 13
deviceIds.kitbot-launcher = 15
deviceIds.kitbot-intake = 14

operator.default-speed = 1.0
operator.slow-speed =  0.4

# Set the controller types
operator.controller-type = PS4
drive.controller-type = PS4

drive.uses-drive-krakens = false
drive.max-module-speed = 15.5
drive.max-rotations-per-second = 1.5
drive.track-width = 20.75
drive.wheel-base = 20.75
drive.drive-gear-ratio = 6.746031746031747
drive.turn-gear-ratio = 21.428571428571427
drive.wheel-diameter = 3.955520515081079
drive.wheel-cof = 1
drive.current-limit = 360
drive.drive-kp = 0.15751
drive.drive-ki = 0
drive.drive-kd = 0
drive.drive-ks = 0.067703
drive.drive-kv = 2.4746
drive.drive-ka = 0.36888
drive.drive-ramp-rate = 0.1
drive.turn-kp = 0.02
drive.turn-ki = 0
drive.turn-kd = 0.01
drive.turn-ks = 0
drive.turn-kv = 0
drive.turn-ka = 0
drive.rotation-tolerance = 0.01
drive.front-left-offset = -0.65380859375
drive.front-right-offset = -0.073974609375
drive.back-left-offset = -0.82666015625
drive.back-right-offset = -0.55419921875
