moi = 6.883
weight = 115
has-canivore = false

drive.uses-drive-krakens = false
drive.max-module-speed = 15.5
drive.max-rotations-per-second = 1.5
drive.track-width = 20.75
drive.wheel-base = 20.75
drive.drive-gear-ratio = 6.746031746031747
drive.turn-gear-ratio = 21.428571428571427
drive.wheel-diameter = 3.955520515081079
drive.wheel-cof = 1
drive.current-limit = 360
drive.drive-kp = 0.15751
drive.drive-ki = 0
drive.drive-kd = 0
drive.drive-ks = 0.067703
drive.drive-kv = 2.4746
drive.drive-ka = 0.36888
drive.drive-ramp-rate = 0.1
drive.turn-kp = 0.02
drive.turn-ki = 0
drive.turn-kd = 0.01
drive.turn-ks = 0
drive.turn-kv = 0
drive.turn-ka = 0
drive.front-left-offset = -0.14404296875
drive.front-right-offset = -0.081787109375
drive.back-left-offset = -0.325927734375
drive.back-right-offset = -0.557373046875
