moi = 6.883
weight = 115
has-canivore = true

# if battery is in back, i.e., tusk
battery-back = true

deviceIds.front-left-steer = 1
deviceIds.front-left-drive = 2
deviceIds.front-left-steer-encoder = 3
deviceIds.front-right-steer = 4
deviceIds.front-right-drive = 5
deviceIds.front-right-steer-encoder = 6
deviceIds.back-left-steer = 10
deviceIds.back-left-drive = 11
deviceIds.back-left-steer-encoder = 12
deviceIds.back-right-steer = 7
deviceIds.back-right-drive = 8
deviceIds.back-right-steer-encoder = 9
deviceIds.pigeon = 13
deviceIds.left-launcher = 14
deviceIds.right-launcher = 15
deviceIds.hood = 23
deviceIds.hood-encoder = 22
deviceIds.kitbot-launcher = 15
deviceIds.kitbot-intake = 14
deviceIds.indexer = 16
deviceIds.intake-driver = 18
deviceIds.intake-pivot = 19
deviceIds.led = 21
deviceIds.intake-beam-break = 0
deviceIds.indexer-beam-break = 1

operator.driver-controller-port = 0
operator.operator-controller-port = 1
operator.operator-controller-deadband = 0.1
operator.default-speed = 1.0
operator.slow-speed = 0.4

# Set the controller types
operator.controller-type = PS5
drive.controller-type = PS5

drive.uses-drive-krakens = true
drive.max-module-speed = 4.8
drive.max-rotations-per-second = 1.5
drive.track-width = 20.753888
drive.wheel-base = 20.753888
drive.drive-gear-ratio = 6.746031746031747
drive.turn-gear-ratio = 21.428571428571427
drive.wheel-diameter = 0.1016
drive.wheel-cof = 1
drive.current-limit = 103
drive.drive-kp = 2.7141
drive.drive-ki = 0
drive.drive-kd = 0
drive.drive-ks = 0.067703
drive.drive-kv = 2.4746
drive.drive-ka = 0.36888
drive.drive-ramp-rate = 0.1
drive.turn-kp = 0.02
drive.turn-ki = 0
drive.turn-kd = 0.01
drive.turn-ks = 0
drive.turn-kv = 0
drive.turn-ka = 0
drive.rotation-tolerance = 0.01
drive.front-left-offset = -0.888427734375
drive.front-right-offset = -0.098388671875
drive.back-left-offset = -0.72509765625
drive.back-right-offset = -0.642822265625
drive.auto-target.kp = 2.7
drive.auto-target.ki = 0.0
drive.auto-target.kd = 0.2

# PathPlanner path-following PID (translation correction)
drive.path-translation-kp = 5.0
drive.path-translation-ki = 0.0
drive.path-translation-kd = 0.0
# PathPlanner path-following PID (rotation correction)
drive.path-rotation-kp = 5.0
drive.path-rotation-ki = 0.0
drive.path-rotation-kd = 0.0

launcher.gear-ratio = 0.8
launcher.hood.gear-ratio = 30.0
launcher.hood.kp = 5.0
launcher.hood.ki = 0.0
launcher.hood.kd = 0.0
# Get the actual offset of the launcher hood
launcher.hood.offset = -0.364990234375
launcher.hood.setpoint-tolerance = 0.1
launcher.hood.manual-modifier = 0.0125
launcher.hood.home-position = 0.0
launcher.hood.min-position = 0
launcher.hood.max-position = 0.84
launcher.kp = 0.1
launcher.ki = 0.0
launcher.kd = 0.0
launcher.velocity-tolerance = 5.0
launcher.idle-velocity = 70.0
launcher.launch-velocity = 110.0
launcher.reverse-velocity = 50.0
launcher.off-velocity = 0.0

indexer.gear-ratio = 1
indexer.kp = 1.0
indexer.ki = 0.0
indexer.kd = 0.0
indexer.off-voltage = 0.0
indexer.index-voltage = 12.0
indexer.extake-voltage = -12.0

intake.driver.gear-ratio = 0.6
intake.pivot.gear-ratio = 26.666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666
intake.driver.kp = 1.0
intake.driver.ki = 0.0
intake.driver.kd = 0.0
intake.pivot.kp = 25.0
intake.pivot.ki = 0.0
intake.pivot.kd = 0.0
intake.driver.off-voltage = 0.0
intake.driver.intake-voltage = 12.0
intake.driver.extake-voltage = -12.0
intake.stuck-on-ball-threshold = 23.0
intake.pivot.setpoint-tolerance = 0.025
intake.pivot.manual-modifier = 0.005
intake.pivot.min-position = 0.0
intake.pivot.max-position = 0.099609
intake.pivot.home-position = 0.0
intake.pivot.jostle-position = 0.0473635
intake.pivot.hold-position = 0.094727
intake.pivot.out-position = 0.099609

# LED information
led.slot-0.start = 8
led.slot-0.end = 84